Create database bankmanagementsystem;
show databases;
use bankmanagementsystem;
create table signup(formno varchar(20), name varchar(20), father_name varchar(20), dob varchar(20), gender varchar(20), email varchar(30), marital_status varchar(20), address varchar(50), city varchar(30), zip varchar(20), state varchar(30));
show tables;
select * from signup; 
create table signupTwo(formno varchar(20), reigion varchar(20), category varchar(20), income varchar(20), education varchar(20), occupation varchar(20), pan varchar(20), CNIC varchar(20), seniorcitizen varchar(20), existingaccount varchar(20));
create table signupthree(formno varchar(20), accountType varchar(40), cardnumber varchar(25), pin varchar(20), facility varchar(100)); 
create table login(formno varchar(20), cardnumber varchar(25), pin varchar(10));
select * from signupthree;
select * from login;
create table bank(pin varchar(20), date varchar(50),type varchar(20),amount varchar(20));
select* from bank;
select * from signupTwo;